- hosts: 'localhost'
  become: false
  vars:
    image_name: veselinovv/python-app
    image_tag: v0.2
    application_directory: /tmp/app
  tasks:
    - name: 'Create {{application_directory}} application_directory'
      file:
        name: '{{ application_directory }}'
        state: directory
    - name: 'Checkout repository'
      git:
        repo: 'git@github.com:veselinovviktor/TestDokcerintegration.git'
        dest: '{{ application_directory }}'
        version: main
        update: true
    - name: 'Build Docker image'
      community.docker.docker_image:
        build:
          path: '{{ application_directory }}'
          dockerfile: Dockerfile
        name: '{{ image_name }}'
        tag: '{{ image_tag }}'
        push: true
        source: build
        state: present
    - name: 'Run Docker container from build image'
      community.docker.docker_container:
        name: python_web
        state: started
        image: '{{ image_name }}:{{ image_tag }}'
        ports:
          - '5001:5000'
