- hosts: localhost
  become: 'no'
  vars_files:
   - ansible_vault.yml
  vars:
    image_name: veselinovv/python-app
    image_tag: v0.2
    application_directory: /tmp/app
  tasks:
    - name: 'Create {{application_directory}} application_directory'
      file:
        name: '{{ application_directory }}'
        state: directory
        mode: 493
    - name: 'Checkout repository'
      git:
        repo: 'git@github.com:veselinovviktor/TelerikDevOpsCourse.git'
        dest: '{{ application_directory }}'
        version: secrets-management
        update: true
        force: true
    - name: Log in to docker
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
    - name: Build Docker image
      docker_image:
        build:
          path: '{{ application_directory }}'
          dockerfile: Dockerfile
        name: '{{ image_name }}'
        tag: '{{ image_tag }}'
        push: true
        source: build
        state: present
    - name: Run Docker container from build image
      docker_container:
        name: python_web
        state: started
        image: '{{ image_name }}:{{ image_tag }}'
        ports:
          - '5001:5000'
