- hosts: localhost
  become: no

  vars:
    image_name: "veselinovv/python-app"
    image_tag: "v0.2"
    application_directory: "/tmp/app"

  tasks:
    - name: Create {{application_directory}} application_directory
      file:
        name: "{{ application_directory }}"
        state: directory
        mode: 0755

    - name: Checkout repository
      git:
        repo: git@github.com:veselinovviktor/TelerikDevOpsCourse.git
        dest: "{{ application_directory }}"
        version: main
        update: true

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ application_directory }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: true
        source: build
        docker_host: "unix://{{ ansible_env.HOME }}/.rd/docker.sock"
        state: present