name: Publish Python image to docker hub
on:
    [workflow_dispatch]

jobs:
    publish_image:
        runs-on: ubintu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: build
              run: |
                cd python_app &&
                docker build . -t docker build . -t veselinovv/python-app:latest
            - name: publish
              run: |
                docker login -u veselinovv -p ${{secrets.DOCKER_HUB_TOKEN}}
                docker push veselinovv/python-app:latest
